-- ============================================================================
-- CareWatch : amorçage des référentiels à partir des données du code (généré le 2026-09-03)
-- À exécuter après referentiels_schema.sql. Rejouable : les lignes existantes sont mises à jour, pas dupliquées.
-- ============================================================================

-- 1. Établissements (73)
insert into public.etablissements (id, nom, nom_complet, type, ville, canton) values
  ('ge-hug-cluse', 'HUG — Cluse-Roseraie', 'HUG — Cluse-Roseraie (site principal)', 'Hôpital universitaire', 'Genève', 'GE'),
  ('ge-hug-mat', 'HUG — Maternité', 'HUG — Maternité', 'Hôpital universitaire', 'Genève', 'GE'),
  ('ge-hug-enf', 'HUG — Hôpital des Enfants', 'HUG — Hôpital des Enfants', 'Hôpital universitaire', 'Genève', 'GE'),
  ('ge-hug-belle', 'HUG — Belle-Idée', 'HUG — Belle-Idée (Psychiatrie)', 'Hôpital universitaire', 'Chêne-Bourg', 'GE'),
  ('ge-hug-trois', 'HUG — Trois-Chêne', 'HUG — Trois-Chêne (Gériatrie)', 'Hôpital universitaire', 'Thônex', 'GE'),
  ('ge-hug-loex', 'HUG — Loëx', 'HUG — Loëx (Réhabilitation)', 'Hôpital universitaire', 'Bernex', 'GE'),
  ('ge-grangettes', 'Clinique des Grangettes', 'Clinique des Grangettes', 'Clinique privée', 'Chêne-Bougeries', 'GE'),
  ('ge-tour', 'Hôpital de la Tour', 'Hôpital de la Tour', 'Clinique privée', 'Meyrin', 'GE'),
  ('ge-beaulieu', 'Clinique Générale Beaulieu', 'Clinique Générale Beaulieu', 'Clinique privée', 'Genève', 'GE'),
  ('ge-colline', 'Hirslanden La Colline', 'Hirslanden Clinique La Colline', 'Clinique privée', 'Genève', 'GE'),
  ('ge-carouge', 'Clinique de Carouge', 'Clinique de Carouge', 'Clinique privée', 'Carouge', 'GE'),
  ('ge-belmont', 'Clinique Belmont', 'Clinique Belmont', 'Clinique privée', 'Genève', 'GE'),
  ('ge-jolimont', 'Clinique de Joli-Mont', 'Clinique de Joli-Mont', 'Clinique privée', 'Genève', 'GE'),
  ('ge-cite', 'Cité Générations', 'Cité Générations — Maison de santé', 'Centre de santé', 'Onex', 'GE'),
  ('ge-grand-saleve', 'Clinique du Grand-Salève', 'Clinique du Grand-Salève (emeis)', 'Clinique psychiatrique privée', 'Veyrier', 'GE'),
  ('vd-chuv', 'CHUV', 'CHUV — Site principal (Lausanne)', 'Hôpital universitaire', 'Lausanne', 'VD'),
  ('vd-chuv-mat', 'CHUV — Maternité', 'CHUV — Maternité', 'Hôpital universitaire', 'Lausanne', 'VD'),
  ('vd-chuv-enf', 'CHUV — Hôpital de l''enfance', 'CHUV — Hôpital de l''enfance', 'Hôpital universitaire', 'Lausanne', 'VD'),
  ('vd-unisante', 'Unisanté', 'Unisanté — Centre universitaire de médecine générale', 'Centre universitaire', 'Lausanne', 'VD'),
  ('vd-pmu', 'PMU', 'Policlinique Médicale Universitaire', 'Centre universitaire', 'Lausanne', 'VD'),
  ('vd-riviera', 'Hôpital Riviera-Chablais', 'Hôpital Riviera-Chablais', 'Hôpital régional', 'Rennaz', 'VD'),
  ('vd-ehnv-yverdon', 'eHnv — Yverdon', 'eHnv — Yverdon-les-Bains', 'Hôpital régional', 'Yverdon-les-Bains', 'VD'),
  ('vd-ehnv-orbe', 'eHnv — Orbe', 'eHnv — Site d''Orbe', 'Hôpital régional', 'Orbe', 'VD'),
  ('vd-ehc-morges', 'EHC — Morges', 'EHC — Morges', 'Hôpital régional', 'Morges', 'VD'),
  ('vd-ehc-aubonne', 'Hôpital d''Aubonne', 'EHC — Aubonne', 'Hôpital régional', 'Aubonne', 'VD'),
  ('vd-ghol-nyon', 'GHOL - Nyon', 'GHOL — Nyon', 'Hôpital régional', 'Nyon', 'VD'),
  ('vd-ghol-rolle', 'GHOL - Rolle', 'GHOL — Rolle', 'Hôpital régional', 'Rolle', 'VD'),
  ('vd-pays-enhaut', 'Hôpital du Pays-d''Enhaut', 'Hôpital du Pays-d''Enhaut', 'Hôpital régional', 'Château-d''Oex', 'VD'),
  ('vd-source', 'Clinique de La Source', 'Clinique de La Source', 'Clinique privée', 'Lausanne', 'VD'),
  ('vd-boiscerf', 'Clinique Bois-Cerf', 'Hirslanden Clinique Bois-Cerf', 'Clinique privée', 'Lausanne', 'VD'),
  ('vd-cecil', 'Clinique Cecil', 'Hirslanden Clinique Cecil', 'Clinique privée', 'Lausanne', 'VD'),
  ('vd-montchoisi', 'Clinique de Montchoisi', 'Clinique de Montchoisi', 'Clinique privée', 'Lausanne', 'VD'),
  ('vd-cery', 'Hôpital de Cery', 'CHUV — Hôpital de Cery (Psychiatrie)', 'Hôpital psychiatrique universitaire', 'Prilly', 'VD'),
  ('vd-prangins', 'Hôpital de Prangins', 'CHUV — Hôpital de Prangins (Psychiatrie)', 'Hôpital psychiatrique universitaire', 'Prangins', 'VD'),
  ('vd-cpnvd', 'Centre Psychiatrie Nord Vaudois', 'CHUV — Centre de Psychiatrie du Nord Vaudois', 'Hôpital psychiatrique universitaire', 'Yverdon-les-Bains', 'VD'),
  ('vd-nant', 'Fondation de Nant', 'Fondation de Nant — Secteur Psychiatrique Est Vaudois', 'Hôpital psychiatrique', 'Corsier-sur-Vevey', 'VD'),
  ('vd-metairie', 'Clinique La Métairie', 'Clinique La Métairie (emeis)', 'Clinique psychiatrique privée', 'Nyon', 'VD'),
  ('vd-bois-bougy', 'Clinique Bois-Bougy', 'Clinique Bois-Bougy (emeis)', 'Clinique de réadaptation', 'Nyon', 'VD'),
  ('vd-samaritain', 'Hôpital du Samaritain', 'Hôpital du Samaritain', 'Hôpital régional', 'Vevey', 'VD'),
  ('vs-sion', 'Hôpital du Valais - Sion', 'Hôpital du Valais — Sion', 'Hôpital cantonal', 'Sion', 'VS'),
  ('vs-martigny', 'Hôpital du Valais - Martigny', 'Hôpital du Valais — Martigny', 'Hôpital cantonal', 'Martigny', 'VS'),
  ('vs-sierre', 'Hôpital du Valais - Sierre', 'Hôpital du Valais — Sierre', 'Hôpital cantonal', 'Sierre', 'VS'),
  ('vs-viege', 'Spitalzentrum Oberwallis', 'Spitalzentrum Oberwallis — Viège', 'Hôpital cantonal', 'Viège', 'VS'),
  ('vs-brigue', 'Hôpital du Valais - Brigue', 'Hôpital du Valais — Brigue', 'Hôpital cantonal', 'Brigue', 'VS'),
  ('vs-valere', 'Clinique de Valère', 'Clinique de Valère', 'Clinique privée', 'Sion', 'VS'),
  ('vs-loeche', 'Clinique de Loèche-les-Bains', 'Clinique de réadaptation de Loèche-les-Bains', 'Clinique privée', 'Loèche-les-Bains', 'VS'),
  ('vs-malevoz', 'Hôpital de Malévoz', 'Hôpital du Valais — Malévoz (Psychiatrie)', 'Hôpital psychiatrique', 'Monthey', 'VS'),
  ('vs-psychiatrie-brig', 'PZO Brigue', 'Psychiatriezentrum Oberwallis — Brigue', 'Hôpital psychiatrique', 'Brigue', 'VS'),
  ('vs-leukerbad', 'Leukerbad Clinic', 'Leukerbad Clinic', 'Clinique de réadaptation', 'Loèche-les-Bains', 'VS'),
  ('fr-fribourg', 'HFR Fribourg', 'HFR — Fribourg', 'Hôpital cantonal', 'Fribourg', 'FR'),
  ('fr-riaz', 'HFR Riaz', 'HFR — Riaz', 'Hôpital cantonal', 'Riaz', 'FR'),
  ('fr-meyriez', 'HFR Meyriez', 'HFR — Meyriez-Murten', 'Hôpital cantonal', 'Meyriez', 'FR'),
  ('fr-tafers', 'HFR Tafers', 'HFR — Tafers', 'Hôpital cantonal', 'Tafers', 'FR'),
  ('fr-steanne', 'Clinique Ste-Anne', 'Clinique Générale Ste-Anne', 'Clinique privée', 'Fribourg', 'FR'),
  ('fr-rfsm-marsens', 'RFSM Marsens', 'RFSM — Marsens', 'Hôpital psychiatrique', 'Marsens', 'FR'),
  ('fr-rfsm-vsg', 'RFSM Villars-sur-Glâne', 'RFSM — Villars-sur-Glâne', 'Hôpital psychiatrique', 'Villars-sur-Glâne', 'FR'),
  ('fr-billens', 'HFR Billens', 'HFR — Billens', 'Hôpital cantonal', 'Billens', 'FR'),
  ('fr-daler', 'Hôpital Daler', 'Hôpital Daler', 'Clinique privée', 'Fribourg', 'FR'),
  ('ne-pourtales', 'HNE Pourtalès', 'HNE — Pourtalès', 'Hôpital cantonal', 'Neuchâtel', 'NE'),
  ('ne-chaux', 'HNE La Chaux-de-Fonds', 'HNE — La Chaux-de-Fonds', 'Hôpital cantonal', 'La Chaux-de-Fonds', 'NE'),
  ('ne-val', 'HNE Val-de-Travers', 'HNE — Val-de-Travers', 'Hôpital cantonal', 'Couvet', 'NE'),
  ('ne-locle', 'HNE Le Locle', 'HNE — Le Locle', 'Hôpital cantonal', 'Le Locle', 'NE'),
  ('ne-cnp', 'CNP', 'CNP — Centre Neuchâtelois de Psychiatrie', 'Hôpital spécialisé', 'Neuchâtel', 'NE'),
  ('ne-prefargier', 'Préfargier', 'CNP — Préfargier', 'Hôpital psychiatrique', 'Marin-Epagnier', 'NE'),
  ('ne-montbrillant', 'Clinique Montbrillant', 'Clinique Montbrillant (Swiss Medical Network)', 'Clinique privée', 'La Chaux-de-Fonds', 'NE'),
  ('ne-providence', 'Hôpital de la Providence', 'Hôpital de la Providence (Swiss Medical Network)', 'Clinique privée', 'Neuchâtel', 'NE'),
  ('ju-delemont', 'H-JU Delémont', 'HJU — Delémont', 'Hôpital cantonal', 'Delémont', 'JU'),
  ('ju-porrentruy', 'H-JU Porrentruy', 'HJU — Porrentruy', 'Hôpital cantonal', 'Porrentruy', 'JU'),
  ('ju-saignelegier', 'H-JU Saignelégier', 'HJU — Saignelégier', 'Hôpital cantonal', 'Saignelégier', 'JU'),
  ('ju-bellelay', 'Centre Bellelay', 'Centre de Réhabilitation Psychiatrique de Bellelay', 'Hôpital psychiatrique', 'Bellelay', 'JU'),
  ('be-stimier', 'HJB Saint-Imier', 'HJB — Saint-Imier', 'Hôpital régional', 'Saint-Imier', 'BE'),
  ('be-moutier', 'HJB Moutier', 'HJB — Moutier', 'Hôpital régional', 'Moutier', 'BE'),
  ('be-bellelay-psy', 'SPJ Bellelay', 'SPJ — Bellelay', 'Hôpital psychiatrique', 'Bellelay', 'BE')
on conflict (id) do update set nom = excluded.nom, nom_complet = excluded.nom_complet, type = excluded.type, ville = excluded.ville, canton = excluded.canton;

-- 2. Catégories de services (15) : remplacées intégralement
delete from public.services_categories;
insert into public.services_categories (ordre, categorie, contextes, items) values
  (1, 'Urgences & Soins critiques', '["general","pediatric","maternity"]'::jsonb, '["Déchocage","Réanimation","SMUR / Ambulances","Soins intensifs adultes","Soins intensifs pédiatriques","Soins intermédiaires","Urgences adultes","Urgences gynécologiques","Urgences pédiatriques"]'::jsonb),
  (2, 'Consultations', '["all"]'::jsonb, '["Consultation ambulatoire spécialisée","Consultation d''anesthésie","Consultation de la douleur","Consultation externe générale","Consultation préopératoire","Policlinique"]'::jsonb),
  (3, 'Hospitalisation', '["all"]'::jsonb, '["Court séjour","Hospitalisation de jour / ambulatoire","Hospitalisation générale","Long séjour / Soins continus","Moyen séjour","Unité de soins palliatifs"]'::jsonb),
  (4, 'Maternité & Périnatalité', '["general","maternity"]'::jsonb, '["Consultations prénatales","Échographie obstétricale","Maternité (post-partum)","Néonatologie","PMA (Procréation médicalement assistée)","Salle d''accouchement","Soins intensifs néonatals"]'::jsonb),
  (5, 'Pédiatrie', '["general","pediatric"]'::jsonb, '["Chirurgie pédiatrique","Pédiatrie générale","Pédiatrie spécialisée","Pédopsychiatrie"]'::jsonb),
  (6, 'Chirurgie', '["general"]'::jsonb, '["Bloc opératoire","Chirurgie ambulatoire","Chirurgie cardiaque","Chirurgie générale","Chirurgie orthopédique","Chirurgie plastique","Chirurgie thoracique","Chirurgie traumatologique","Chirurgie vasculaire","Chirurgie viscérale","Neurochirurgie"]'::jsonb),
  (7, 'Spécialités médicales', '["general"]'::jsonb, '["Allergologie","Cardiologie","Dermatologie","Endocrinologie / Diabétologie","Gastro-entérologie","Gériatrie","Hématologie","Hépatologie","Immunologie","Infectiologie","Médecine interne","Médecine tropicale","Néphrologie / Dialyse","Neurologie","Oncologie","Pneumologie","Rhumatologie"]'::jsonb),
  (8, 'Psychiatrie & Santé mentale', '["general","psychiatric"]'::jsonb, '["Addictologie","Hospitalisation psychiatrique","Psychiatrie adulte","Psychiatrie de liaison","Troubles alimentaires","Unité de crise"]'::jsonb),
  (9, 'Gynécologie', '["general","maternity"]'::jsonb, '["Colposcopie","Gynécologie générale","Gynécologie oncologique","Sénologie (sein)"]'::jsonb),
  (10, 'ORL & Spécialités sensorielles', '["general"]'::jsonb, '["Audiologie","Ophtalmologie","ORL (Oto-rhino-laryngologie)","Phoniatrie","Stomatologie"]'::jsonb),
  (11, 'Imagerie & Diagnostic', '["all"]'::jsonb, '["Échographie","IRM","Médecine nucléaire (PET-CT)","Radiologie conventionnelle","Radiologie interventionnelle","Scanner (CT)"]'::jsonb),
  (12, 'Laboratoire & Pathologie', '["all"]'::jsonb, '["Génétique médicale","Laboratoire d''analyses","Pathologie / Anatomopathologie","Prélèvements sanguins"]'::jsonb),
  (13, 'Rééducation & Réadaptation', '["general","rehabilitation","geriatric"]'::jsonb, '["Ergothérapie","Logopédie","Neuropsychologie","Physiothérapie","Réadaptation cardiovasculaire","Réadaptation musculo-squelettique","Réadaptation neurologique"]'::jsonb),
  (14, 'Services support', '["all"]'::jsonb, '["Accueil / Réception / Admission","Aumônerie / Accompagnement spirituel","Diététique","Facturation / Caisse","Interprétariat","Pharmacie hospitalière","Service social","Transport patients"]'::jsonb),
  (15, 'Autres', '["all"]'::jsonb, '["Autre service","Centre de dépistage","Centre de vaccination","Médecine du sport","Médecine du travail","Médecine légale"]'::jsonb);

-- 3. Services propres à certains établissements (154) : remplacés intégralement
delete from public.services_etablissement;
insert into public.services_etablissement (etablissement_id, ordre, categorie, items) values
  ('ge-hug-cluse', 1, 'Urgences & Soins aigus', '["Urgences adultes","Déchocage","Soins intensifs adultes","Soins intermédiaires","SMUR"]'::jsonb),
  ('ge-hug-cluse', 2, 'Médecine', '["Médecine interne générale","Cardiologie","Pneumologie","Gastro-entérologie","Néphrologie / Dialyse","Neurologie","Endocrinologie / Diabétologie","Rhumatologie","Infectiologie","Hématologie","Immunologie / Allergologie","Oncologie","Dermatologie","Médecine tropicale","Hépatologie"]'::jsonb),
  ('ge-hug-cluse', 3, 'Chirurgie', '["Chirurgie viscérale","Chirurgie orthopédique","Chirurgie cardiaque","Chirurgie thoracique","Chirurgie vasculaire","Neurochirurgie","Chirurgie plastique","Chirurgie ambulatoire","Bloc opératoire"]'::jsonb),
  ('ge-hug-cluse', 4, 'Spécialités sensorielles', '["Ophtalmologie","ORL","Stomatologie"]'::jsonb),
  ('ge-hug-cluse', 5, 'Imagerie & Diagnostic', '["Radiologie","Scanner (CT)","IRM","Médecine nucléaire (PET-CT)","Échographie"]'::jsonb),
  ('ge-hug-cluse', 6, 'Laboratoire', '["Laboratoire central","Pathologie","Génétique médicale","Prélèvements sanguins"]'::jsonb),
  ('ge-hug-cluse', 7, 'Consultations', '["Consultation ambulatoire","Policlinique de médecine","Consultation de la douleur","Consultation préopératoire","Consultation d''anesthésie"]'::jsonb),
  ('ge-hug-cluse', 8, 'Hospitalisation', '["Hospitalisation générale","Court séjour","Hospitalisation de jour","Soins palliatifs"]'::jsonb),
  ('ge-hug-cluse', 9, 'Services support', '["Accueil / Admission","Service social","Diététique","Pharmacie","Aumônerie","Interprétariat","Facturation","Transport patients"]'::jsonb),
  ('ge-hug-mat', 1, 'Maternité', '["Salle d''accouchement","Post-partum","Consultations prénatales","Échographie obstétricale","Grossesses à risque"]'::jsonb),
  ('ge-hug-mat', 2, 'Néonatologie', '["Néonatologie","Soins intensifs néonatals"]'::jsonb),
  ('ge-hug-mat', 3, 'Gynécologie', '["Gynécologie générale","Gynécologie oncologique","PMA (Procréation assistée)","Sénologie","Urgences gynécologiques"]'::jsonb),
  ('ge-hug-mat', 4, 'Services support', '["Accueil / Admission","Service social","Interprétariat","Lactation / Allaitement"]'::jsonb),
  ('ge-hug-enf', 1, 'Pédiatrie', '["Urgences pédiatriques","Pédiatrie générale","Soins intensifs pédiatriques","Néonatologie"]'::jsonb),
  ('ge-hug-enf', 2, 'Spécialités pédiatriques', '["Chirurgie pédiatrique","Pédopsychiatrie","Neuropédiatrie","Onco-hématologie pédiatrique","Cardiopédiatrie","Gastro-entérologie pédiatrique","Pneumologie pédiatrique","Endocrinologie pédiatrique"]'::jsonb),
  ('ge-hug-enf', 3, 'Services support', '["Accueil / Admission","Service social","Interprétariat","École à l''hôpital"]'::jsonb),
  ('ge-hug-belle', 1, 'Psychiatrie', '["Psychiatrie adulte","Hospitalisation psychiatrique","Unité de crise","Psychiatrie de liaison","Addictologie","Troubles alimentaires","Psychiatrie forensique"]'::jsonb),
  ('ge-hug-belle', 2, 'Consultations', '["Consultation ambulatoire psychiatrique","Centre de jour","Programme thérapeutique ambulatoire"]'::jsonb),
  ('ge-hug-belle', 3, 'Services support', '["Accueil / Admission","Service social","Ergothérapie","Aumônerie"]'::jsonb),
  ('ge-hug-trois', 1, 'Gériatrie', '["Gériatrie aiguë","Réadaptation gériatrique","Unité de soins palliatifs","Consultation mémoire","Psychogériatrie"]'::jsonb),
  ('ge-hug-trois', 2, 'Rééducation', '["Physiothérapie","Ergothérapie","Logopédie","Neuropsychologie"]'::jsonb),
  ('ge-hug-trois', 3, 'Services support', '["Accueil / Admission","Service social","Diététique","Aumônerie"]'::jsonb),
  ('ge-hug-loex', 1, 'Réhabilitation', '["Réadaptation musculo-squelettique","Réadaptation neurologique","Réadaptation cardiovasculaire","Réadaptation respiratoire"]'::jsonb),
  ('ge-hug-loex', 2, 'Rééducation', '["Physiothérapie","Ergothérapie","Logopédie","Neuropsychologie"]'::jsonb),
  ('ge-hug-loex', 3, 'Services support', '["Accueil / Admission","Service social","Diététique"]'::jsonb),
  ('vd-chuv', 1, 'Urgences & Soins aigus', '["Urgences adultes","Déchocage","Soins intensifs adultes","Soins intermédiaires","SMUR"]'::jsonb),
  ('vd-chuv', 2, 'Médecine', '["Médecine interne","Cardiologie","Pneumologie","Gastro-entérologie","Néphrologie / Dialyse","Neurologie","Endocrinologie / Diabétologie","Rhumatologie","Infectiologie","Hématologie","Immunologie / Allergologie","Oncologie","Dermatologie"]'::jsonb),
  ('vd-chuv', 3, 'Chirurgie', '["Chirurgie viscérale","Chirurgie orthopédique","Chirurgie cardiaque","Chirurgie thoracique","Chirurgie vasculaire","Neurochirurgie","Chirurgie plastique","Chirurgie ambulatoire","Bloc opératoire"]'::jsonb),
  ('vd-chuv', 4, 'Spécialités', '["Ophtalmologie","ORL","Stomatologie","Urologie","Gynécologie"]'::jsonb),
  ('vd-chuv', 5, 'Imagerie & Diagnostic', '["Radiologie","Scanner (CT)","IRM","Médecine nucléaire","Radiologie interventionnelle"]'::jsonb),
  ('vd-chuv', 6, 'Laboratoire', '["Laboratoire central","Pathologie","Génétique médicale","Prélèvements sanguins"]'::jsonb),
  ('vd-chuv', 7, 'Consultations', '["Policlinique médicale","Consultation de la douleur","Consultation préopératoire"]'::jsonb),
  ('vd-chuv', 8, 'Hospitalisation', '["Hospitalisation générale","Court séjour","Hospitalisation de jour","Soins palliatifs"]'::jsonb),
  ('vd-chuv', 9, 'Services support', '["Accueil / Admission","Service social","Diététique","Pharmacie","Aumônerie","Interprétariat","Facturation","Transport patients"]'::jsonb),
  ('vd-chuv-mat', 1, 'Maternité', '["Salle d''accouchement","Post-partum","Consultations prénatales","Échographie obstétricale","Grossesses à risque"]'::jsonb),
  ('vd-chuv-mat', 2, 'Néonatologie', '["Néonatologie","Soins intensifs néonatals"]'::jsonb),
  ('vd-chuv-mat', 3, 'Gynécologie', '["Gynécologie générale","Gynécologie oncologique","PMA (Procréation assistée)","Sénologie","Urgences gynécologiques"]'::jsonb),
  ('vd-chuv-mat', 4, 'Services support', '["Accueil / Admission","Service social","Interprétariat"]'::jsonb),
  ('vd-chuv-enf', 1, 'Pédiatrie', '["Urgences pédiatriques","Pédiatrie générale","Soins intensifs pédiatriques"]'::jsonb),
  ('vd-chuv-enf', 2, 'Spécialités pédiatriques', '["Chirurgie pédiatrique","Pédopsychiatrie","Neuropédiatrie","Onco-hématologie pédiatrique"]'::jsonb),
  ('vd-chuv-enf', 3, 'Services support', '["Accueil / Admission","Service social","Interprétariat"]'::jsonb),
  ('vd-riviera', 1, 'Urgences', '["Urgences adultes","Soins intensifs","Soins intermédiaires"]'::jsonb),
  ('vd-riviera', 2, 'Médecine', '["Médecine interne","Cardiologie","Pneumologie","Gastro-entérologie","Neurologie","Oncologie","Néphrologie"]'::jsonb),
  ('vd-riviera', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie ambulatoire","Bloc opératoire"]'::jsonb),
  ('vd-riviera', 4, 'Maternité', '["Maternité","Gynécologie","Néonatologie"]'::jsonb),
  ('vd-riviera', 5, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('vd-riviera', 6, 'Services support', '["Accueil / Admission","Service social","Pharmacie","Facturation"]'::jsonb),
  ('vd-cery', 1, 'Psychiatrie adulte', '["Psychiatrie générale","Hospitalisation psychiatrique","Unité de crise","Unité fermée","Psychiatrie de liaison"]'::jsonb),
  ('vd-cery', 2, 'Programmes spécialisés', '["Addictologie","Troubles alimentaires","Troubles de la personnalité","Psychiatrie forensique","Programme premiers épisodes psychotiques"]'::jsonb),
  ('vd-cery', 3, 'Ambulatoire', '["Consultation ambulatoire","Centre de jour","Programme thérapeutique ambulatoire"]'::jsonb),
  ('vd-cery', 4, 'Services support', '["Accueil / Admission","Service social","Ergothérapie","Aumônerie"]'::jsonb),
  ('vd-prangins', 1, 'Psychiatrie', '["Psychiatrie adulte","Hospitalisation psychiatrique","Unité de crise","Psychiatrie de l''âge avancé"]'::jsonb),
  ('vd-prangins', 2, 'Programmes spécialisés', '["Addictologie","Troubles de l''humeur","Réhabilitation psychiatrique"]'::jsonb),
  ('vd-prangins', 3, 'Ambulatoire', '["Consultation ambulatoire","Centre de jour"]'::jsonb),
  ('vd-prangins', 4, 'Services support', '["Accueil / Admission","Service social","Ergothérapie"]'::jsonb),
  ('vd-unisante', 1, 'Médecine de premier recours', '["Médecine générale","Policlinique médicale","Consultation sans rendez-vous"]'::jsonb),
  ('vd-unisante', 2, 'Spécialités', '["Médecine des voyages et des migrations","Médecine du travail","Médecine du sport","Santé sexuelle"]'::jsonb),
  ('vd-unisante', 3, 'Prévention', '["Vaccination","Dépistage","Centre de compétences en santé publique"]'::jsonb),
  ('vd-unisante', 4, 'Services support', '["Accueil","Service social","Interprétariat"]'::jsonb),
  ('vd-ehc-morges', 1, 'Urgences', '["Urgences adultes","Soins intensifs"]'::jsonb),
  ('vd-ehc-morges', 2, 'Médecine', '["Médecine interne","Cardiologie","Gastro-entérologie","Oncologie","Neurologie"]'::jsonb),
  ('vd-ehc-morges', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie ambulatoire"]'::jsonb),
  ('vd-ehc-morges', 4, 'Autres', '["Gynécologie","Centre de la douleur","Radiologie","Laboratoire"]'::jsonb),
  ('vd-ehc-morges', 5, 'Services support', '["Accueil / Admission","Service social","Pharmacie","Facturation"]'::jsonb),
  ('vd-ehnv-yverdon', 1, 'Urgences', '["Urgences adultes","Soins intensifs"]'::jsonb),
  ('vd-ehnv-yverdon', 2, 'Médecine', '["Médecine interne","Cardiologie","Gastro-entérologie","Pneumologie","Neurologie"]'::jsonb),
  ('vd-ehnv-yverdon', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie ambulatoire"]'::jsonb),
  ('vd-ehnv-yverdon', 4, 'Maternité', '["Maternité","Gynécologie","Néonatologie"]'::jsonb),
  ('vd-ehnv-yverdon', 5, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('vd-ehnv-yverdon', 6, 'Services support', '["Accueil / Admission","Service social","Pharmacie"]'::jsonb),
  ('ge-grangettes', 1, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie plastique","Chirurgie ambulatoire"]'::jsonb),
  ('ge-grangettes', 2, 'Maternité', '["Maternité","Salle d''accouchement","Néonatologie","Gynécologie","PMA (Procréation assistée)"]'::jsonb),
  ('ge-grangettes', 3, 'Spécialités', '["Cardiologie","Oncologie","Ophtalmologie","ORL","Urologie","Gastro-entérologie"]'::jsonb),
  ('ge-grangettes', 4, 'Imagerie', '["Radiologie","Scanner","IRM","Échographie"]'::jsonb),
  ('ge-grangettes', 5, 'Services support', '["Accueil / Admission","Facturation"]'::jsonb),
  ('ge-tour', 1, 'Urgences', '["Urgences adultes","Urgences pédiatriques"]'::jsonb),
  ('ge-tour', 2, 'Médecine', '["Médecine interne","Cardiologie","Gastro-entérologie","Neurologie","Oncologie","Pneumologie"]'::jsonb),
  ('ge-tour', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie ambulatoire"]'::jsonb),
  ('ge-tour', 4, 'Maternité', '["Maternité","Gynécologie"]'::jsonb),
  ('ge-tour', 5, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('ge-tour', 6, 'Services support', '["Accueil / Admission","Service social","Facturation"]'::jsonb),
  ('ge-beaulieu', 1, 'Chirurgie', '["Chirurgie orthopédique","Chirurgie viscérale","Chirurgie plastique","Chirurgie ambulatoire"]'::jsonb),
  ('ge-beaulieu', 2, 'Spécialités', '["Cardiologie","Ophtalmologie","ORL","Urologie","Gastro-entérologie","Gynécologie"]'::jsonb),
  ('ge-beaulieu', 3, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('ge-beaulieu', 4, 'Services support', '["Accueil / Admission","Facturation"]'::jsonb),
  ('ge-colline', 1, 'Chirurgie', '["Chirurgie orthopédique","Chirurgie viscérale","Chirurgie urologique","Chirurgie ambulatoire"]'::jsonb),
  ('ge-colline', 2, 'Spécialités', '["Cardiologie","Gastro-entérologie","Gynécologie","Ophtalmologie"]'::jsonb),
  ('ge-colline', 3, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('ge-colline', 4, 'Services support', '["Accueil / Admission","Facturation"]'::jsonb),
  ('vs-sion', 1, 'Urgences & Soins aigus', '["Urgences adultes","Déchocage","Soins intensifs","SMUR"]'::jsonb),
  ('vs-sion', 2, 'Médecine', '["Médecine interne","Cardiologie","Pneumologie","Gastro-entérologie","Néphrologie / Dialyse","Neurologie","Endocrinologie","Rhumatologie","Infectiologie","Hématologie","Oncologie","Dermatologie","Angiologie"]'::jsonb),
  ('vs-sion', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique / Traumatologie","Chirurgie vasculaire","Chirurgie viscérale","Neurochirurgie","Chirurgie ambulatoire"]'::jsonb),
  ('vs-sion', 4, 'Maternité', '["Maternité","Gynécologie","Gynécologie oncologique","PMA"]'::jsonb),
  ('vs-sion', 5, 'Autres', '["Ophtalmologie","ORL","Pédiatrie","Centre de la douleur","Radio-oncologie"]'::jsonb),
  ('vs-sion', 6, 'Imagerie', '["Radiologie","Scanner","IRM","PET-CT","Médecine nucléaire","Radiologie interventionnelle"]'::jsonb),
  ('vs-sion', 7, 'Services support', '["Accueil / Admission","Service social","Pharmacie","Diététique","Aumônerie","Facturation"]'::jsonb),
  ('vs-martigny', 1, 'Urgences', '["Urgences adultes"]'::jsonb),
  ('vs-martigny', 2, 'Médecine', '["Médecine interne","Cardiologie","Gastro-entérologie","Pneumologie","Neurologie"]'::jsonb),
  ('vs-martigny', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie ambulatoire"]'::jsonb),
  ('vs-martigny', 4, 'Réadaptation', '["Réadaptation musculo-squelettique","Gériatrie"]'::jsonb),
  ('vs-martigny', 5, 'Services support', '["Accueil / Admission","Service social","Facturation"]'::jsonb),
  ('vs-sierre', 1, 'Urgences', '["Urgences adultes"]'::jsonb),
  ('vs-sierre', 2, 'Médecine', '["Médecine interne","Gériatrie","Soins palliatifs"]'::jsonb),
  ('vs-sierre', 3, 'Chirurgie', '["Chirurgie ambulatoire"]'::jsonb),
  ('vs-sierre', 4, 'Réadaptation', '["Réadaptation gériatrique","Réadaptation musculo-squelettique"]'::jsonb),
  ('vs-sierre', 5, 'Services support', '["Accueil / Admission","Service social","Facturation"]'::jsonb),
  ('vs-malevoz', 1, 'Psychiatrie', '["Psychiatrie adulte","Hospitalisation psychiatrique","Unité de crise","Unité fermée"]'::jsonb),
  ('vs-malevoz', 2, 'Programmes', '["Addictologie","Psychiatrie de l''âge avancé","Réhabilitation psychiatrique"]'::jsonb),
  ('vs-malevoz', 3, 'Ambulatoire', '["Consultation ambulatoire","Centre de jour"]'::jsonb),
  ('vs-malevoz', 4, 'Services support', '["Accueil / Admission","Service social","Ergothérapie"]'::jsonb),
  ('fr-fribourg', 1, 'Urgences & Soins aigus', '["Urgences adultes","Soins intensifs","Soins intermédiaires","Stroke Unit"]'::jsonb),
  ('fr-fribourg', 2, 'Médecine', '["Médecine interne","Cardiologie","Chirurgie cardiaque","Pneumologie","Gastro-entérologie","Néphrologie / Dialyse","Neurologie","Neurochirurgie","Endocrinologie / Diabétologie","Rhumatologie","Infectiologie","Oncologie","Dermatologie","Angiologie"]'::jsonb),
  ('fr-fribourg', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique / Traumatologie","Chirurgie viscérale","Chirurgie plastique","Chirurgie ambulatoire"]'::jsonb),
  ('fr-fribourg', 4, 'Maternité & Pédiatrie', '["Maternité","Gynécologie","Néonatologie","Pédiatrie"]'::jsonb),
  ('fr-fribourg', 5, 'Spécialités', '["Ophtalmologie","ORL","Urologie","Soins palliatifs"]'::jsonb),
  ('fr-fribourg', 6, 'Imagerie', '["Radiologie","Scanner","IRM","Médecine nucléaire"]'::jsonb),
  ('fr-fribourg', 7, 'Rééducation', '["Physiothérapie","Ergothérapie"]'::jsonb),
  ('fr-fribourg', 8, 'Services support', '["Accueil / Admission","Service social","Diététique","Pharmacie","Aumônerie","Facturation"]'::jsonb),
  ('fr-riaz', 1, 'Urgences', '["Permanence médicale"]'::jsonb),
  ('fr-riaz', 2, 'Médecine', '["Médecine interne","Gériatrie"]'::jsonb),
  ('fr-riaz', 3, 'Chirurgie', '["Chirurgie ambulatoire"]'::jsonb),
  ('fr-riaz', 4, 'Rééducation', '["Physiothérapie","Ergothérapie"]'::jsonb),
  ('fr-riaz', 5, 'Services support', '["Accueil / Admission","Service social"]'::jsonb),
  ('fr-rfsm-marsens', 1, 'Psychiatrie', '["Psychiatrie adulte","Hospitalisation psychiatrique","Unité de crise","Psychiatrie de l''âge avancé"]'::jsonb),
  ('fr-rfsm-marsens', 2, 'Programmes', '["Addictologie","Troubles alimentaires","Réhabilitation psychiatrique"]'::jsonb),
  ('fr-rfsm-marsens', 3, 'Ambulatoire', '["Consultation ambulatoire","Centre de jour"]'::jsonb),
  ('fr-rfsm-marsens', 4, 'Services support', '["Accueil / Admission","Service social","Ergothérapie"]'::jsonb),
  ('ne-pourtales', 1, 'Urgences & Soins aigus', '["Urgences adultes","SMUR","Soins intensifs","Unité cérébrovasculaire (Stroke)"]'::jsonb),
  ('ne-pourtales', 2, 'Médecine', '["Médecine interne","Cardiologie","Pneumologie","Gastro-entérologie","Neurologie","Néphrologie","Oncologie","Rhumatologie","Infectiologie"]'::jsonb),
  ('ne-pourtales', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie ambulatoire"]'::jsonb),
  ('ne-pourtales', 4, 'Centre mère-enfant', '["Maternité","Gynécologie","Pédiatrie","Néonatologie"]'::jsonb),
  ('ne-pourtales', 5, 'Spécialités', '["Ophtalmologie","ORL","Centre de l''obésité"]'::jsonb),
  ('ne-pourtales', 6, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('ne-pourtales', 7, 'Services support', '["Accueil / Admission","Service social","Pharmacie","Facturation"]'::jsonb),
  ('ne-chaux', 1, 'Urgences', '["Urgences adultes","Soins intensifs"]'::jsonb),
  ('ne-chaux', 2, 'Médecine', '["Médecine interne","Cardiologie","Gastro-entérologie","Neurologie","Oncologie"]'::jsonb),
  ('ne-chaux', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie ambulatoire"]'::jsonb),
  ('ne-chaux', 4, 'Spécialités', '["Gynécologie","Centre du sein certifié","Sénologie"]'::jsonb),
  ('ne-chaux', 5, 'Imagerie', '["Radiologie","Scanner","IRM","Médecine nucléaire / PET-CT"]'::jsonb),
  ('ne-chaux', 6, 'Services support', '["Accueil / Admission","Service social","Pharmacie","Facturation"]'::jsonb),
  ('ne-cnp', 1, 'Psychiatrie', '["Psychiatrie adulte","Hospitalisation psychiatrique","Unité de crise","Pédopsychiatrie"]'::jsonb),
  ('ne-cnp', 2, 'Programmes', '["Addictologie","Psychiatrie de l''âge avancé","Psychiatrie de liaison"]'::jsonb),
  ('ne-cnp', 3, 'Ambulatoire', '["Consultation ambulatoire","Centre de jour"]'::jsonb),
  ('ne-cnp', 4, 'Services support', '["Accueil / Admission","Service social","Ergothérapie"]'::jsonb),
  ('ju-delemont', 1, 'Urgences', '["Urgences adultes"]'::jsonb),
  ('ju-delemont', 2, 'Médecine', '["Médecine interne","Cardiologie","Gastro-entérologie","Pneumologie","Oncologie"]'::jsonb),
  ('ju-delemont', 3, 'Chirurgie', '["Chirurgie générale","Chirurgie orthopédique","Chirurgie viscérale","Chirurgie ambulatoire"]'::jsonb),
  ('ju-delemont', 4, 'Maternité', '["Maternité","Gynécologie"]'::jsonb),
  ('ju-delemont', 5, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('ju-delemont', 6, 'Services support', '["Accueil / Admission","Service social","Facturation"]'::jsonb),
  ('vd-source', 1, 'Chirurgie', '["Chirurgie orthopédique","Chirurgie viscérale","Chirurgie plastique","Chirurgie ambulatoire"]'::jsonb),
  ('vd-source', 2, 'Spécialités', '["Cardiologie","Gastro-entérologie","Gynécologie","Oncologie","Ophtalmologie","ORL","Urologie"]'::jsonb),
  ('vd-source', 3, 'Imagerie', '["Radiologie","Scanner","IRM"]'::jsonb),
  ('vd-source', 4, 'Services support', '["Accueil / Admission","Facturation"]'::jsonb);

-- 4. Organisations et numéros d'urgence (16) : remplacés intégralement
delete from public.organisations;
insert into public.organisations (type, ordre, nom, nom_complet, telephone, description, url, ville) values
  ('urgence', 1, '144 - Urgences médicales', null, '144', 'Ambulance, urgences vitales 24h/24', null, null),
  ('urgence', 2, '143 - La Main Tendue', null, '143', 'Écoute et soutien psychologique 24h/24', null, null),
  ('urgence', 3, '142 - Aide aux victimes de violences', null, '142', 'Ligne nationale gratuite et confidentielle, 24h/24, pour toute violence physique, psychique ou sexuelle, et pour les proches. Pas un numéro d''urgence : en danger immédiat, 117 ou 144.', null, null),
  ('urgence', 4, '147 - Aide pour les jeunes', null, '147', 'Ligne d''aide pour enfants et adolescents', null, null),
  ('urgence', 5, '117 - Police', null, '117', 'En cas de danger immédiat', null, null),
  ('organisation', 1, 'FAANG', 'Fédération des Associations d''Afrodescendant·e·s et de Noir·e·s de Genève', '+41 22 301 16 50', 'Médiation interculturelle, advocacy', 'https://faang.ch', 'Genève'),
  ('organisation', 2, 'Afro-Cité', 'Forum Afro-Cité (FAANG)', null, 'Espace de dialogue et de mobilisation citoyenne sur les enjeux des communautés afrodescendantes à Genève', 'https://faang.ch/afro-cite', 'Genève'),
  ('organisation', 3, 'APSR-GE', 'APSR — Genève', null, 'Réseau de professionnels de santé racisés, pair-aidance, formations', 'https://instagram.com/apsr_ge', 'Genève'),
  ('organisation', 4, 'Suisse Drépano', 'Association Suisse de la Drépanocytose', '+41 79 128 63 68', 'Soutien aux patient·e·s drépanocytaires et leurs familles', 'https://suisse-drepano.ch', 'Suisse'),
  ('organisation', 5, 'Centre LAVI Genève', 'Centre de consultation pour victimes d''infractions', '+41 22 320 01 02', 'Aide juridique et psychologique aux victimes de discrimination', 'https://centrelavi-ge.ch', 'Genève'),
  ('organisation', 6, 'Appartenances', 'Appartenances Genève', '+41 22 341 42 00', 'Consultations psychothérapeutiques pour migrants, médiation', 'https://appartenances-geneve.ch', 'Genève'),
  ('organisation', 7, 'Pluriels', 'Pluriels — Centre de consultations', '+41 22 908 42 42', 'Consultations psychiatriques et psychothérapeutiques transculturelles', null, 'Genève'),
  ('organisation', 8, 'Caritas Genève', 'Caritas Genève', '+41 22 708 04 44', 'Aide sociale, accompagnement santé pour personnes précarisées', 'https://caritas-geneve.ch', 'Genève'),
  ('organisation', 9, 'CSP Genève', 'Centre Social Protestant', '+41 22 807 27 07', 'Consultations juridiques, aide sociale', 'https://csp.ch', 'Genève'),
  ('organisation', 10, 'Resilia (KimboCare)', 'Resilia — Navigation santé', null, 'Plateforme de navigation dans le système de santé', 'https://resilia.kimbocare.com', 'Genève'),
  ('organisation', 11, 'Convivens Lab', 'Convivens Lab (HES-SO)', null, 'Coordination technique & scientifique CareWatch™', 'https://convivens.ch', 'Genève');

-- 5. Ressources cantonales (25) : remplacées intégralement
delete from public.ressources_cantonales;
insert into public.ressources_cantonales (canton, type, ordre, nom, telephone, url, email, adresse, description) values
  ('GE', 'mediation', 1, 'Espace Médiation des HUG', '022 372 22 28', 'https://www.hug.ch/espace-mediation', 'espace.mediation@hug.ch', null, 'Facilite la communication entre patient·e et équipe soignante. Indépendant de la hiérarchie médicale.'),
  ('GE', 'mediation', 2, 'Médiateurs assermentés du canton (domaine santé)', null, 'https://www.ge.ch/faire-appel-au-mediateur-cantonal/autres-instances-mediation', null, null, 'Personne neutre, indépendante de l’hôpital comme des autorités. Service gratuit.'),
  ('GE', 'plainte', 1, 'Commission de surveillance des professions de la santé et des droits des patients (CSPSDP)', '022 546 89 50', 'https://www.ge.ch/surveillance-professions-sante-droit-patients', null, 'Rue du Conseil-Général 3-5, 1205 Genève', 'Procédure gratuite. Peut ouvrir une enquête et prononcer des sanctions. Plainte par écrit. Permanence lu-je 9h-11h / 14h-16h.'),
  ('GE', 'lavi', 3, 'Centre LAVI Genève', '022 320 01 02', 'https://centrelavi-ge.ch', null, null, 'Aide gratuite et confidentielle aux victimes d’infractions. Soutien psychologique, juridique et social. Lu-ve sur rendez-vous.'),
  ('VD', 'mediation', 1, 'Bureau cantonal de médiation santé et social', '021 316 09 86', 'https://www.vd.ch/sante-soins-et-handicap/patients-et-residents-droits-et-qualite-de-soins/plaintes-pour-patients-et-residents-droits-des-patients/bureau-cantonal-de-mediation-sante-et-social', 'info.mediation@vd.ch', null, 'Service gratuit, indépendant et confidentiel. Médiatrices en totale indépendance vis-à-vis des parties et des autorités.'),
  ('VD', 'plainte', 1, 'Commission d’examen des plaintes des patients et résidents', '021 316 09 85', 'https://www.vd.ch/sante-soins-et-handicap/patients-et-residents-droits-et-qualite-de-soins/plaintes-pour-patients-et-residents-droits-des-patients/commission-dexamen-des-plaintes-des-patients-residents-ou-usagers-detablissements-sanitaires-et-detablissements-socio-educatifs', null, null, 'Peut prononcer des sanctions (avertissement, blâme, amende). Plainte écrite, datée et signée.'),
  ('VD', 'plainte', 2, 'Office du médecin cantonal — signalement de dysfonctionnement', null, 'https://www.vd.ch/prestation/deposer-une-plainte-aupres-de-loffice-du-medecin-cantonal-en-cas-de-dysfonctionnement-dun-fournisseur-de-soins', null, null, 'Pour témoignages, plaintes, dénonciations ou questions sur les droits des patients. Rend un avis ou prend des mesures.'),
  ('VD', 'lavi', 3, 'Centre LAVI Vaud (Lausanne, Aigle, Nyon, Yverdon)', '021 631 03 00', 'https://www.lavi.ch', null, null, 'Aide gratuite et confidentielle. Accompagnement psychologique, juridique et social. Sur rendez-vous.'),
  ('VS', 'mediation', 1, 'Ombudsman de la santé et des institutions sociales', '027 321 27 17', 'https://www.ombudsman-vs.ch', 'info@ombudsman-vs.ch', null, 'Organe neutre et indépendant créé par le Conseil d’État. Permanence ma 14h-17h et je 9h-12h. Procédure gratuite.'),
  ('VS', 'mediation', 2, 'Espace d’écoute de l’Hôpital du Valais', null, 'https://www.hopitalvs.ch', null, null, 'Instance interne d’écoute et de dialogue au sein de l’hôpital.'),
  ('VS', 'plainte', 1, 'Bureau des plaintes — Service de la santé publique', '027 606 49 00', 'https://www.vs.ch/web/ssp/droits-des-patients', 'SSP-BDP-BS@admin.vs.ch', null, 'Collecte les plaintes et signalements des patients et des employés. Accepte les signalements anonymes.'),
  ('VS', 'lavi', 3, 'Centre LAVI Valais romand', '027 607 31 00', 'https://www.vs.ch/web/sas/lavi', null, 'Rue des Vergers 1, 1950 Sion', 'Aide gratuite et confidentielle. Entretien sur rendez-vous uniquement.'),
  ('FR', 'mediation', 1, 'Commission de surveillance des professions de la santé et des droits des patients et patientes', '026 305 29 13', 'https://www.fr.ch/dsas/ssp/autorisations-surveillance-des-institutions-et-professionnels-de-la-sante', null, null, 'Peut proposer une médiation. Si échec, instruit la plainte. Pas de délai pour saisir la commission (prescription : 10 ans).'),
  ('FR', 'plainte', 1, 'Direction de la santé et des affaires sociales (DSAS)', '026 305 29 13', 'https://www.fr.ch/sante/prevention-et-promotion/connaitre-ses-droits-comme-patient', null, null, 'La commission peut agir d’office, sur plainte ou sur dénonciation écrite. Prescription : 10 ans.'),
  ('FR', 'lavi', 3, 'Centre LAVI Fribourg', '026 305 15 80', 'https://www.fr.ch', null, null, 'Aide aux victimes : enfants, hommes, victimes de la circulation. Sur rendez-vous.'),
  ('FR', 'lavi', 4, 'Solidarité femmes — Centre LAVI', '026 322 22 02', 'https://www.sf-lavi.ch', null, null, 'Permanence 7j/7 pour les femmes victimes de violence. Lu-ve 9h-12h / 14h-17h30.'),
  ('NE', 'mediation', 1, 'Autorité de conciliation en matière de santé (ACMS)', '032 889 62 00', 'https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/droits-patients/Pages/accueil.aspx', null, null, 'Rattachée au Service de la santé publique. Tente la conciliation avant toute procédure formelle.'),
  ('NE', 'plainte', 1, 'Autorité de surveillance des professions de la santé et des institutions', '032 889 62 00', 'https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/droits-patients/Pages/accueil.aspx', null, null, 'Examine les violations des devoirs professionnels et du respect des droits des patients. Requête par écrit obligatoire.'),
  ('NE', 'lavi', 3, 'Centre LAVI Neuchâtel', '032 889 66 49', 'https://www.ne.ch', null, 'Rue Pourtalès 1, 2000 Neuchâtel / Rue Daniel-Jeanrichard 43, La Chaux-de-Fonds', 'Aide gratuite et confidentielle. Urgences 24h/24 via SAVI : 0800 880 480.'),
  ('JU', 'mediation', 1, 'Médiatrice cantonale en santé', '032 420 51 20', 'https://www.jura.ch', 'mediation-sante@jura.ch', null, 'Nommée par le Gouvernement. Entend les doléances et tente de concilier les parties. En cas d’échec, oriente vers la commission.'),
  ('JU', 'plainte', 1, 'Commission de surveillance des droits des patients', '032 420 51 20', 'https://www.jura.ch', 'president.csdp@jura.ch', null, 'Créée en 2008. Traite les plaintes des citoyen·ne·s estimant que leurs droits n’ont pas été respectés dans la relation de soins.'),
  ('JU', 'lavi', 3, 'Centre LAVI Jura', '032 420 81 00', 'https://www.jura.ch', 'lavi@ssrju.ch', 'Quai de la Sorne 22, 2800 Delémont', 'Aide gratuite et confidentielle aux victimes d’infractions.'),
  ('BE', 'mediation', 1, 'Service de médiation pour le secteur hospitalier du canton de Berne', '031 633 79 31', 'https://www.gef.be.ch', null, null, 'Médiation uniquement pour les patients hospitalisés. Pas de médiation pour les consultations ambulatoires.'),
  ('BE', 'plainte', 1, 'Direction de la santé, des affaires sociales et de l’intégration', '031 633 79 20', 'https://www.gef.be.ch', null, null, 'Traitement des plaintes des patients à l’encontre des professionnels et des institutions de santé.'),
  ('BE', 'lavi', 3, 'Centre LAVI Biel/Bienne', '032 322 56 33', 'https://www.opferhilfe-bern.ch', null, 'Rue de l’Argent 4, 2502 Biel/Bienne', 'Aide gratuite pour la population francophone du Jura bernois et de Bienne.');

-- 6. Actualités (9)
insert into public.actualites (id, date_affichee, titre, resume, source, type, url) values
  (1, '28 jan 2026', 'Lancement de CareWatch™ en Suisse romande', 'L''observatoire participatif de l''équité des soins est désormais accessible dans tous les cantons romands. Plus de 50 établissements sont déjà référencés.', 'CareWatch™', 'announcement', null),
  (2, '15 jan 2026', 'Rapport OBSAN : Iniquités dans les expériences de soins en Suisse', 'Cette étude propose une analyse des iniquités relatives à l''expérience de la qualité des soins. Les résultats montrent des disparités significatives selon l''origine des patient·e·s.', 'OBSAN', 'research', 'https://www.obsan.admin.ch/fr/publications/2023-iniquites-dans-les-experiences-des-soins-en-suisse'),
  (3, '10 jan 2026', 'Swiss Health Network for Equity : Accès aux soins pour toutes et tous', 'Le réseau publie des recommandations pour l''adaptation des services cliniques aux besoins de certains groupes de patient·e·s et l''empowerment des personnes défavorisées.', 'SHNE', 'policy', 'https://www.health-equity-network.ch/fr/themen/chancengleichheit-im-gesundheitswesen'),
  (4, '5 jan 2026', 'BAG/OFSP : Équité dans le système de santé suisse', 'La Confédération rappelle que le système de santé doit permettre à chacun de bénéficier de prestations adaptées, indépendamment de son sexe, origine ou statut socio-économique.', 'BAG', 'policy', 'https://www.bag.admin.ch/bag/fr/home/strategie-und-politik/nationale-gesundheitsstrategien/gesundheitliche-chancengleichheit.html'),
  (5, '20 déc 2025', 'Étude Unisanté : Indicateurs de l''équité dans les soins', 'Les résultats montrent une corrélation claire entre les hospitalisations potentiellement évitables et les inégalités socio-économiques en Suisse.', 'Unisanté', 'research', 'https://www.unisante.ch/fr/formation-recherche/recherche/publications'),
  (6, '15 déc 2025', 'Revue Médicale Suisse : L''équité des soins, un enjeu majeur', 'Article de P. Bodenmann sur les défis de l''équité des soins en Suisse et les pistes d''amélioration pour les professionnels de santé.', 'RMS', 'research', 'https://www.revmed.ch/revue-medicale-suisse/2019/revue-medicale-suisse-640/l-equite-des-soins-un-enjeu-majeur-qui-nous-concerne'),
  (7, '1 déc 2025', 'swimsa : Prise de position sur l''équité en santé', 'Les étudiant·e·s en médecine suisses appellent à intégrer l''équité dans les études, les systèmes de soin et les institutions à travers la Suisse.', 'swimsa', 'policy', 'https://www.swimsa.ch/fr/positions'),
  (8, '25 nov 2025', 'SLHS : Recommandations pour un monitoring qualité en Suisse', 'Le Swiss Learning Health System publie un rapport mandaté par la Commission fédérale pour la qualité, proposant des modèles de tableaux de bord et de reporting public pour le système de santé suisse.', 'SLHS', 'research', 'https://www.slhs.ch/en/latest-news/posts/quality-monitoring-and-public-reporting-in-the-swiss-healthcare-system-recommendations-released/'),
  (9, '9 déc 2025', 'Learning Healthcare Project : Réaliser le potentiel des systèmes apprenants', 'Rapport de Newcastle University sur les cadres, outils et défis de l''implémentation de Learning Health Systems dans différents contextes nationaux, avec des études de cas dans 20 pays.', 'Learning Healthcare Project', 'research', 'https://learninghealthcareproject.org/realising-the-potential-of-learning-health-systems/')
on conflict (id) do update set date_affichee = excluded.date_affichee, titre = excluded.titre, resume = excluded.resume, source = excluded.source, type = excluded.type, url = excluded.url;
select setval('public.actualites_id_seq', (select coalesce(max(id), 1) from public.actualites));

-- Contrôle
select (select count(*) from public.etablissements) as etablissements, (select count(*) from public.services_categories) as categories, (select count(*) from public.services_etablissement) as services_etab, (select count(*) from public.organisations) as organisations, (select count(*) from public.ressources_cantonales) as ressources, (select count(*) from public.actualites) as actualites;